# Generated by Django 4.1.3 on 2022-11-15 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileshomework',
            name='file',
            field=models.FileField(upload_to='docs/homework-files/%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='imagehomeworks',
            name='image',
            field=models.ImageField(upload_to='images/uploaded/%Y-%m-%d'),
        ),
    ]
